# Generated by Django 3.0.9 on 2020-08-03 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='hidden',
            field=models.BooleanField(default=False),
        ),
    ]
