# Generated by Django 3.0.8 on 2020-08-04 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_photo_hidden'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='pic',
            field=models.FileField(blank=True, null=True, upload_to='babylon'),
        ),
    ]
