# Generated by Django 3.0.8 on 2020-08-04 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_photo_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='url',
            field=models.CharField(blank=True, max_length=250, unique=True),
        ),
    ]
